name: Manual Upload to Azure Blob (kubestrong)

on:
  workflow_dispatch:  # 手动触发

jobs:
  manual-upload:
    name: Upload kubestrong data to Azure Blob
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload users.json and avatars to Azure Blob
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Uploading kubestrong/users.json..."
            az storage blob upload \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              --container-name user-info \
              --name kubestrong/users.json \
              --file users.json \
              --overwrite

            echo "Uploading kubestrong avatars..."
            for file in avatars/*; do
              filename=$(basename "$file")
              az storage blob upload \
                --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
                --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
                --container-name user-info \
                --name kubestrong/avatars/$filename \
                --file $file \
                --overwrite
            done
